---
- hosts: Terraform_server
  become: yes
  tasks:
    - name: nginx latest version check
      apt: name=nginx state=latest

    - name: "start nginx"
      service: 
        name: nginx
        state: started