---
- hosts: all
  become: yes
  vars:
    - Message1: How are you Today?

  tasks:

  - name: "apt-get update"
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install git
    apt:
      name: git
      state: present
      update_cache: yes
        
  - name: Install npm
    apt:
      name: npm
      state: present
      update_cache: yes

  - name: Install Nodejs
    apt:
      name: nodejs
      state: present
      update_cache: yes
    
  - name: Install pm2
    npm:
      name: pm2
      global: yes

  - name: Install nginx
    apt:
      name: ['nginx']
      state: latest
      update_cache: yes

  - name: Delete existing file
    file:
        path: /var/www/html/index.nginx-debian.html
        state: absent
    
  - name: restart nginx
    service:
        name: nginx
        state: restarted

  - name: Clone a github repository
    git:
       repo: https://github.com/lucaspittam/node-graphql-react-chat-app.git
       dest: /var/www/html
       clone: yes
       update: yes
       force: yes
  
  - name: Go to Repo folder and npm install
    command:
      chdir: /var/www/html
      cmd:  npm install


  - name: Go to  Repo folder and npm run build
    command:
      chdir: /var/www/html
      cmd:  sudo npm run build

  - name: Go to  Repo folder and npm start
    command:
      chdir: /var/www/html
      cmd:  sudo npm start

  
 # - name:  npm init
  #  command:
   #   chdir: /var/www/html/frontend/build 
    #  cmd:  npm init -y
  
 # - name:  Start
  #  command:
   #   chdir: /var/www/html/frontend/build 
    #  cmd:  npm run index.js