---
- hosts: all
  become: yes
  vars:
    - Message1: How are you Today?

  tasks:

  - name: "apt-get update"
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install git
    apt:
      name: git
      state: present
      update_cache: yes
        
  - name: Install npm
    apt:
      name: npm
      state: present
      update_cache: yes

  - name: Install Nodejs
    apt:
      name: nodejs
      state: present
      update_cache: yes
    
  - name: Install pm2
    npm:
      name: pm2
      global: yes

  - name: Clone a github repository
    git:
       repo: https://github.com/lucaspittam/node-graphql-react-chat-app.git
       dest: /home/ubuntu/repo
       clone: yes
       update: yes
       force: yes

  - name: Go to Repo folder and npm install
    command:
      chdir: /home/ubuntu/repo
      cmd:  npm install

  - name: Go to Repo/Client folder and npm install
    command:
      chdir: /home/ubuntu/repo/client
      cmd:  sudo npm install


