name: ansible
on:
  workflow_run:
    workflows: ["Terraform"]
    types:
      - completed

jobs:
  notify:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        if: steps.apply.outcome == 'success'
        with:
           # playbook filepath
          playbook: nginx.yml
          # Optional, directory where playbooks live
          directory: ./ansible
          # Optional, SSH private key
          key: ssh-key.pem
          options: |
            --inventory inventory.yaml
            --verbose
