
name: 'Create_and_Provision'

on:
  workflow_run:
    workflows: ["Create_and_Provision"]
    types:
      - completed

permissions:
  contents: read

jobs:
  Terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: ./terraform
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
        aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        aws-region: '${{ secrets.AWS_REGION }}'

    # Initialize a new or existing Terraform working directory
    - name: Terraform Init
      run: terraform init
      
    
      # Destroy existing infrastructure (If there is any)   
    - name: Terraform Destroy
      run: terraform destroy -auto-approve -input=false  
      
      
      # Validate config plan
    - name: Terraform Validate
      run: terraform validate

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      id: plan
      run: terraform plan -input=false

    # On push to "main", build or change infrastructure according to Terraform config files  
    - name: Terraform Apply
      id: apply
      if: steps.plan.outcome == 'success'
      run: terraform apply -auto-approve -input=false

    # Delay
    - name: Delay
      uses: juliangruber/sleep-action@v1.0.1
      with:
    # Time period as ms or string
        time: 10s
  
 
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      if: steps.apply.outcome == 'success'
      with:
           # playbook filepath
          playbook: playbook.yml
          # directory where playbooks live
          directory: ./ansible
          # SSH private key
          key: ssh-key.pem
          options: |
            --inventory inventory.yaml
            --verbose

