---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: simple Lint Code Base

on:
  push:

  pull_request:
    branches: [master, main]

###############
# Set the Job #
###############
jobs:
  build:
    name: simple code base
    runs-on: ubuntu-latest
    ##################
    # Load all steps #
    ##################
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
